joy_control_node:
  ros__parameters:
    input_topic: '/joy' # Topic in which the input messages are received
    output_topic: '/offboard_velocity_cmd' # Topic in which the output messages are published
    arm_switch_topic: '/arm_message' # Topic in which the arm switch messages are published
    # drone_output_topic: '/' # Topic in which the drone output messages are published
    # Indexes for TX16S joystick axes and buttons
    axis_map:
      set_aileron_index: 0  # Right stick left/right
      set_elevator_index: 1  # Right stick up/down
      set_throttle_index: 2  # Left stick up/down
      set_rudder_index: 3  # Left stick left/right
    button_map:
      set_arm_disarm_index: 3  # SH switch up/down
      # set_mode_index: 5  # SB switch left/mid/right hold/position/offboard
    drone_parameters:    
      lin_speed: 0.5
      turn_speed: 0.2